import { Roboto } from 'next/font/google'

const roboto_init = Roboto({
   subsets: ['latin'],
   weight: ['400', '700'],
   variable: '--font-roboto'
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto_init.variable}>{children}</body>
    </html>
  )
}
